function touch {
    param (
        [Parameter(Mandatory = $true)] 
        [string]$value
    )

    if (Test-Path -LiteralPath $value) {
        (Get-Item -Path $value).LastWriteTime = Get-Date
    }
    else {
        New-Item -Type File -Path $value
    }
}
# SIG # Begin signature block
# MIIFwgYJKoZIhvcNAQcCoIIFszCCBa8CAQExCzAJBgUrDgMCGgUAMGkGCisGAQQB
# gjcCAQSgWzBZMDQGCisGAQQBgjcCAR4wJgIDAQAABBAfzDtgWUsITrck0sYpfvNR
# AgEAAgEAAgEAAgEAAgEAMCEwCQYFKw4DAhoFAAQUDdtWICrbPj8QujIVU2hCkfpK
# +NKgggNLMIIDRzCCAjOgAwIBAgIQhiXs6awyFqFPm3GUeR/E0TAJBgUrDgMCHQUA
# MCwxKjAoBgNVBAMTIVBvd2VyU2hlbGwgTG9jYWwgQ2VydGlmaWNhdGUgUm9vdDAe
# Fw0yMDA3MTExNzM1MThaFw0zOTEyMzEyMzU5NTlaMCMxITAfBgNVBAMTGFBvd2Vy
# U2hlbGwgVGFzbmltLVpvdGRlcjCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoC
# ggEBANRp2DYg1OkCh6u37EASAuwkwmNjVnoonWvdmyQenR1cbV8fZSPFujhO2OZz
# /NNJqP4I3vy9ZD0567JBiWqklESMv3vu7um0L6m/CFk/Jw6sXzT1/ktb6r/+4Q/k
# OROLpCZpq54Sxhc+M21tatB6qHmqyioN4w5l/5lM4fulcA3xj8b5JNEKGFNCL9QV
# Lk0kdfxnZQZ8nOX7FSARAty+ciGcPUXZywNBmdl0sV6MEDjk2QesqLJ3A/kIQ5bN
# dh8zS3v8YWJO1cs4DWtcJm/O54Wve6Kx+6UW5tJDJTwV9odAqfSEGsGCia77xdFq
# ljUVpI095A8nDkZXpxMhLMXY3HECAwEAAaN2MHQwEwYDVR0lBAwwCgYIKwYBBQUH
# AwMwXQYDVR0BBFYwVIAQJJrB//PzkZSRACuhyg6k7qEuMCwxKjAoBgNVBAMTIVBv
# d2VyU2hlbGwgTG9jYWwgQ2VydGlmaWNhdGUgUm9vdIIQCWDLzayPlJdIZSFywc56
# xzAJBgUrDgMCHQUAA4IBAQCNuHeASv1d2yZhusDN7YtvI4R8b/QNO42UZAh5FAHB
# xtuKaeG4I2sbbwpBVR2V0TilRiJxC2ENbi1h9tw8nwNuHOPsXYmfkpNoCAy2uLMA
# nRPqJU3BkSlzXpyOpYUcyPzWtwIkSA+3bMBLF6TJPpcvHGdL8Z/bCi40garSZxgW
# dMj2h75+ZswzInZWG1ptuY6+w9lXIZT5jIfcRi5XuhmcH358xPTBdlRaO4DoYcVt
# 5YKtUlwId1MwuqaA5IMqkjowTCHr/T1aH60d48z1oSntjLz/1rvSUgKOz5Plk4d3
# 0ut469ruQ7WHTrgz6R7HJK5aeWQ8B7NpgaGaFGSOKpupMYIB4TCCAd0CAQEwQDAs
# MSowKAYDVQQDEyFQb3dlclNoZWxsIExvY2FsIENlcnRpZmljYXRlIFJvb3QCEIYl
# 7OmsMhahT5txlHkfxNEwCQYFKw4DAhoFAKB4MBgGCisGAQQBgjcCAQwxCjAIoAKA
# AKECgAAwGQYJKoZIhvcNAQkDMQwGCisGAQQBgjcCAQQwHAYKKwYBBAGCNwIBCzEO
# MAwGCisGAQQBgjcCARUwIwYJKoZIhvcNAQkEMRYEFLoDpA+6V55VhJq9qwWTEMtr
# aQwcMA0GCSqGSIb3DQEBAQUABIIBAIFx7/UomS8wBeKEvoYX7deio6VxrOiLtdSo
# 8OuR/hggdT0HDIbk8vxsMk69Vv9+c/sRRr8Cw6pqgy7hKw7o4RKuI564yBtr95TD
# 5ElwpzCs6U9fZaABrSlprA/pOJHoUTztjD8aAfnDV4BOOvssMGq7bRHxZDgVITZ6
# K3DOv2c04IbbQgCn2uXtalmgGemy6RlkgJh5u8QdlbIzjAfdcuga8ZSpBAywThkg
# KrX6k6dNwHp/Y/fl121S0xFGji9hqk2QE+ADSyEfxaM8StBrakHVHzmrAkj57Sus
# eO0LO085rQTbWEkr2jif71sC6fFdPe/kr3U9Cw4DORAjEHMa2eo=
# SIG # End signature block
